# AUTOGENERATED. DO NOT EDIT BY HAND.
global syscall_table
syscall_table = {}
from .syscall_table_x86_64 import init
init(syscall_table)
from .syscall_table_arm import init
init(syscall_table)
from .syscall_table_arm64 import init
init(syscall_table)
