# AUTOGENERATED. DO NOT EDIT BY HAND.
global syscall_table
syscall_table = {}
import audit_pretty.syscall_table_x86_64
audit_pretty.syscall_table_x86_64.init(syscall_table)
import audit_pretty.syscall_table_arm
audit_pretty.syscall_table_arm.init(syscall_table)
import audit_pretty.syscall_table_arm64
audit_pretty.syscall_table_arm64.init(syscall_table)
